{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2023-28609",
      "ASSIGNER": "cve@mitre.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/ansible-semaphore/semaphore/commit/3e4a62b7f2b1ef0660c9fb839818a53c80a5a8b1",
          "name": "https://github.com/ansible-semaphore/semaphore/commit/3e4a62b7f2b1ef0660c9fb839818a53c80a5a8b1",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.89",
          "name": "https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.89",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "api/auth.go in Ansible Semaphore before 2.8.89 mishandles authentication."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-03-18T21:15Z",
  "lastModifiedDate": "2023-03-20T02:46Z"
}