{
  "id": "CVE-2025-8194",
  "sourceIdentifier": "cna@python.org",
  "published": "2025-07-28T19:15:43.793",
  "lastModified": "2025-08-07T21:15:29.780",
  "vulnStatus": "Awaiting Analysis",
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "There is a defect in the CPython “tarfile” module affecting the “TarFile” extraction and entry enumeration APIs. The tar implementation would process tar archives with negative offsets without error, resulting in an infinite loop and deadlock during the parsing of maliciously crafted tar archives. \n\nThis vulnerability can be mitigated by including the following patch after importing the “tarfile” module:  https://gist.github.com/sethmlarson/1716ac5b82b73dbcbf23ad2eff8b33e1"
    },
    {
      "lang": "es",
      "value": "Existe un defecto en el módulo \"tarfile\" de CPython que afecta a las API de extracción y enumeración de entradas de \"TarFile\". La implementación de tar procesaba archivos tar con desplazamientos negativos sin errores, lo que resultaba en un bucle infinito y un bloqueo durante el análisis de archivos tar manipulados con fines maliciosos. Esta vulnerabilidad se puede mitigar incluyendo el siguiente parche después de importar el módulo \"tarfile\": import tarfile def _block_patched(self, count):     if count &lt; 0: # pragma: no cover         raise tarfile.InvalidHeaderError(\"invalid offset\")     return _block_patched._orig_block(self, count) _block_patched._orig_block = tarfile.TarInfo._block tarfile.TarInfo._block = _block_patched"
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "cna@python.org",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "baseScore": 7.5,
          "baseSeverity": "HIGH",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
      }
    ]
  },
  "weaknesses": [
    {
      "source": "cna@python.org",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-835"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gist.github.com/sethmlarson/1716ac5b82b73dbcbf23ad2eff8b33e1",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/commit/7040aa54f14676938970e10c5f74ea93cd56aa38",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/commit/c9d9f78feb1467e73fd29356c040bde1c104f29f",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/commit/cdae923ffe187d6ef916c0f665a31249619193fe",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/commit/fbc2a0ca9ac8aff6887f8ddf79b87b4510277227",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/issues/130577",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/137027",
      "source": "cna@python.org"
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/ZULLF3IZ726XP5EY7XJ7YIN3K5MDYR2D/",
      "source": "cna@python.org"
    }
  ]
}