{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2023-3361",
      "ASSIGNER": "secalert@redhat.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2216588",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2216588",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/security/cve/CVE-2023-3361",
          "name": "https://access.redhat.com/security/cve/CVE-2023-3361",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/opendatahub-io/odh-dashboard/issues/1415",
          "name": "https://github.com/opendatahub-io/odh-dashboard/issues/1415",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in Red Hat OpenShift Data Science. When exporting a pipeline from the Elyra notebook pipeline editor as Python DSL or YAML, it reads S3 credentials from the cluster (ds pipeline server) and saves them in plain text in the generated output instead of an ID for a Kubernetes secret."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-10-04T12:15Z",
  "lastModifiedDate": "2023-10-04T12:56Z"
}