{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2022-25024",
      "ASSIGNER": "cve@mitre.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/",
          "name": "https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/vinitkumar/json2xml/pull/107/files",
          "name": "https://github.com/vinitkumar/json2xml/pull/107/files",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/vinitkumar/json2xml/pull/107",
          "name": "https://github.com/vinitkumar/json2xml/pull/107",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/vinitkumar/json2xml/issues/106",
          "name": "https://github.com/vinitkumar/json2xml/issues/106",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The json2xml package through 3.12.0 for Python allows an error in typecode decoding enabling a remote attack that can lead to an exception, causing a denial of service."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-08-22T19:16Z",
  "lastModifiedDate": "2023-08-22T20:10Z"
}